/*
##
##  Enhancer for YouTube™
##  =====================
##
##  Author: Maxime RF <https://www.mrfdev.com>
##
##  This file is protected by copyright laws and international copyright
##  treaties, as well as other intellectual property laws and treaties.
##
##  All rights not expressly granted to you are retained by the author.
##  Read the license.txt file for more details.
##
##  © MRFDEV.com - All Rights Reserved
##
*/
((b,F)=>{function g(){var a={};this.name?a[this.name]=this.value:a[this.id]=this.checked;chrome.storage.local.set(a)}function Ma(){for(var a=[],d=0;d<v.length;d++)v[d].checked&&a.push(v[d].id);chrome.storage.local.set({controls:a})}function q(){chrome.storage.local.set({griditemsperrow:e})}function ya(){for(var a={},d=0;d<n.length;d++)a[n[d].name]=n[d].value;chrome.storage.local.set({customcolors:a})}function Q(){for(var a="youtube-deep-dark-custom"===b.querySelector('input[name="theme"]:checked').value?
!1:!0,d=0;d<n.length;d++)n[d].disabled=a;R.disabled=a}function za(){fetch(chrome.runtime.getURL(`_locales/${r}/messages.json`)).then(a=>a.json()).then(a=>{S=a.locale_dir.message;b.documentElement.lang=r.replace("_","-");b.body.dir=S;for(var d=B.length-1;0<=d;d--)B[d].textContent=a[B[d].dataset.text].message;for(d=p.length-1;0<=d;d--)p[d].dataset.tooltip=a[p[d].dataset.message].message;b.querySelector("#customcss").setAttribute("placeholder",a.custom_theme_instructions.message);b.querySelector("#customscript").setAttribute("placeholder",
a.custom_script_instructions.message);chrome.storage.local.set({localecode:r,localedir:S})})}function qa(a){b.body.classList.add("overflow-hidden");G.style.display="block";a.style.display="block";a.scrollTop=0;G.classList.add("in");setTimeout(()=>{b.body.classList.add("modal-open");a.querySelector("button.close-modal").focus()},50)}function Aa(a){b.body.classList.remove("modal-open");setTimeout(()=>{a.style.display="none";G.classList.add("fade");G.classList.remove("in");setTimeout(()=>{G.style.display=
"none";b.body.classList.remove("overflow-hidden");"donate-modal"===a.id?b.querySelector("nav .donate a").focus():"backup-modal"===a.id&&b.querySelector("fieldset.backup button").focus()},300)},300)}function Ba(){var a=b.querySelector("main"),d=b.createElement("style");d.textContent=`:root{--main-inset-shadow-top:${a.offsetTop}px;--main-inset-shadow-width:${a.clientWidth}px}`;b.head.appendChild(d)}var r=chrome.i18n.getMessage("locale_code"),S=chrome.i18n.getMessage("locale_dir"),B=b.querySelectorAll(".i18n"),
w=b.querySelector("main"),u=b.querySelector(".tooltip"),G=b.querySelector("#modal-backdrop"),n=b.querySelectorAll('#customcolors input[type="color"]'),R=b.querySelector("#reset-custom-colors"),p=b.querySelectorAll(".player-control .info"),v,e;chrome.storage.onChanged.addListener((a,d)=>{for(const l in a)void 0!==a[l].newValue&&("darktheme"===l&&a[l].newValue!==b.querySelector("#darktheme").checked?b.querySelector("#darktheme").click():"theme"===l&&a[l].newValue!==b.querySelector('input[name="theme"]:checked').value?
(b.querySelector(`input[name="theme"][value="${a[l].newValue}"]`).checked=!0,b.querySelector("#themevariant").disabled="enhanced-dark"===a[l].newValue?!1:!0,b.querySelector("#vendorthemevariant").disabled="youtube-deep-dark"===a[l].newValue?!1:!0,Q()):"customtheme"===l&&(d=b.querySelector("#customtheme"),d.checked!==a[l].newValue&&(d.checked=a[l].newValue),b.querySelector("#customcss").disabled=!d.checked,b.querySelector("#customcss-btn").disabled=!d.checked))});chrome.storage.local.get(F,a=>{if(r===
a.localecode){b.documentElement.lang=r.replace("_","-");b.body.dir=S;for(var d=B.length-1;0<=d;d--)B[d].textContent=chrome.i18n.getMessage(B[d].dataset.text);for(d=p.length-1;0<=d;d--)p[d].dataset.tooltip=chrome.i18n.getMessage(p[d].dataset.message);b.querySelector("#customcss").setAttribute("placeholder",chrome.i18n.getMessage("custom_theme_instructions"));b.querySelector("#customscript").setAttribute("placeholder",chrome.i18n.getMessage("custom_script_instructions"))}else r=a.localecode,za();d=
b.querySelectorAll("nav a, aside a");d.forEach(c=>{c.addEventListener("focus",function(){this.parentNode.classList.add("focus")});c.addEventListener("blur",function(){this.parentNode.classList.remove("focus")})});d[0].addEventListener("click",c=>{c.preventDefault();w.scrollTo(0,0)});var l=b.querySelector("nav .donate a"),C=b.querySelector("#donate-modal"),Ca=C.querySelector(".close-modal");l.addEventListener("click",c=>{c.preventDefault();c=0>"bg ca cs da de el es et fi fr hr hu it lt lv nl pl pt_PT ro sk sl sv".indexOf(r)?
"USD":"EUR";C.querySelector(".donate-buttons").dataset.currencyCode=c;qa(C)});C.querySelectorAll(".donate-buttons button").forEach(c=>{c.addEventListener("click",function(){var f=0>"bg ca cs da de el es et fi fr hr hu it lt lv nl pl pt_PT ro sk sl sv".indexOf(r)?"USD":"EUR";f=l.dataset.paypal.replace(/AMOUNT/,this.dataset.amount).replace(/CURRENCY_CODE/,f);chrome.tabs.create({url:f,active:!0})})});Ca.addEventListener("click",()=>{Aa(C)});d=b.querySelector("#locale");d.value=r;d.addEventListener("change",
function(){r=this.value;za()});d.addEventListener("focus",function(){this.parentNode.classList.add("focus")});d.addEventListener("blur",function(){this.parentNode.classList.remove("focus")});b.querySelectorAll("aside a").forEach(c=>{c.addEventListener("click",f=>{f.preventDefault();var k=b.querySelector("fieldset."+f.target.dataset.target);w.scrollTop=0===w.scrollTop?1:w.scrollTop-1;w.addEventListener("scrollend",function Na(){w.removeEventListener("scrollend",Na);k.classList.add("highlighted");k.querySelector("input, textarea, select:not(.hidden), button").focus()});
k.scrollIntoView()})});"#applyvideofilters #blackbars #blockhfrformats #blockwebmformats #boostvolume #cinemamode #cinemamodewideplayer #convertshorts #executescript #expanddescription #hidecardsendscreens #hidechat #hidecomments #hiderelated #hideshorts #newestcomments #reversemousewheeldirection #theatermode #wideplayer #wideplayerviewport".split(" ").forEach(c=>{c=b.querySelector(c);c.checked=a[c.id];c.addEventListener("click",g)});b.querySelector("#keyboard-shortcuts-btn").addEventListener("click",
()=>{chrome.runtime.sendMessage({request:"configure-keyboard-shortcuts"})});v=b.querySelectorAll('.player-control input[type="checkbox"]');for(d=0;d<v.length;d++)v[d].checked=-1<a.controls.indexOf(v[d].id)?!0:!1,v[d].addEventListener("click",Ma);p=b.querySelectorAll(".player-control .info");for(d=p.length-1;0<=d;d--)p[d].addEventListener("click",c=>{c.preventDefault()}),p[d].addEventListener("mouseenter",c=>{c=c.target;var f=c.getBoundingClientRect();u.textContent=c.dataset.tooltip;u.style.setProperty("top",
"calc("+f.top+"px - .5rem)");u.style.setProperty("left",f.left+"px");u.classList.add("visible")}),p[d].addEventListener("mouseleave",()=>{u.classList.remove("visible")});var h=b.querySelectorAll('input[name="controlbaractive"]'),H=b.querySelector("#controlsvisible"),I=b.querySelector("#controlbarposition"),Da=b.querySelector("#control-bar-centering"),J=b.querySelector("#controlbarcentered"),Ea=b.querySelector("#control-bar-visibility"),K=b.querySelector("#controlbarautohide");for(d=0;d<h.length;d++)h[d].value===
String(a.controlbar.active)&&(h[d].checked=!0),h[d].addEventListener("click",function(){"false"===this.value?(a.controlbar.active=!1,H.disabled=!1,I.disabled=!0,J.disabled=!0,K.disabled=!0):(a.controlbar.active=!0,H.disabled=!0,I.disabled=!1,J.disabled=!1,K.disabled=!1);chrome.storage.local.set({controlbar:a.controlbar})});H.checked=a.controlsvisible;H.disabled=a.controlbar.active;H.addEventListener("click",g);I.value=a.controlbar.position;I.disabled=!a.controlbar.active;I.addEventListener("change",
function(){Da.classList["absolute"===this.value?"remove":"add"]("hidden");Ea.classList["fixed"===this.value?"remove":"add"]("hidden");a.controlbar.position=this.value;chrome.storage.local.set({controlbar:a.controlbar})});Da.classList["absolute"===a.controlbar.position?"remove":"add"]("hidden");J.checked=a.controlbar.centered;J.disabled=!a.controlbar.active;J.addEventListener("click",function(){a.controlbar.centered=this.checked;chrome.storage.local.set({controlbar:a.controlbar})});Ea.classList["fixed"===
a.controlbar.position?"remove":"add"]("hidden");K.checked=a.controlbar.autohide;K.disabled=!a.controlbar.active;K.addEventListener("click",function(){a.controlbar.autohide=this.checked;chrome.storage.local.set({controlbar:a.controlbar})});d=b.querySelector("#backdropcolor");h=b.querySelector("#backdropopacity");var Oa=b.querySelector("#opacity"),Pa=b.querySelector("#cinemamode-backdrop"),ra=()=>{var c=a.backdropcolor.replace("#",""),f=parseInt(c.substring(0,2),16),k=parseInt(c.substring(2,4),16);
c=parseInt(c.substring(4,6),16);Oa.textContent=a.backdropopacity+"%";Pa.style.backgroundColor=`rgba(${f}, ${k}, ${c}, ${a.backdropopacity/100})`};d.value=a.backdropcolor;d.addEventListener("input",function(){a.backdropcolor=this.value;ra();chrome.storage.local.set({backdropcolor:this.value})});d.addEventListener("change",g);h.value=a.backdropopacity;h.addEventListener("input",function(){a.backdropopacity=Number(this.value);ra();chrome.storage.local.set({backdropopacity:a.backdropopacity})});ra();
var L=b.querySelector("#playback-speed"),M=b.querySelector("#custom-playback-speed");d=b.querySelector("#overridespeeds");var T=b.querySelector("#speedvariation");h=b.querySelector("#defaultvolume");var U=b.querySelector("#volume"),Fa=b.querySelector("#volume-preview"),t=b.querySelector("#volumemultiplier"),x=b.querySelector("#controlspeed"),V=b.querySelector("#controlspeedmousebutton"),N=b.querySelector("#controlvolume"),W=b.querySelector("#controlvolumemousebutton"),X=b.querySelector("#volumevariation"),
Ga=b.querySelector("#miniplayer"),Y=b.querySelector("#miniplayersize"),Z=b.querySelector("#miniplayerposition");L.value=a.overridespeeds?1:a.speed;L.addEventListener("change",function(){chrome.storage.local.set({speed:parseFloat(this.value)})});M.value=a.overridespeeds?a.speed:1;M.addEventListener("change",function(){chrome.storage.local.set({speed:parseFloat(this.value)})});a.overridespeeds&&(L.classList.add("hidden"),M.classList.remove("hidden"));d.checked=a.overridespeeds;d.addEventListener("click",
function(){T.disabled=!this.checked;var c=b.querySelector("#playback-speed-label");c.classList.add("animated","blink");setTimeout(()=>{c.classList.remove("animated","blink")},2400);L.classList.toggle("hidden");M.classList.toggle("hidden");chrome.storage.local.set({overridespeeds:this.checked,speed:parseFloat(this.checked?M.value:L.value)})});T.value=a.speedvariation;T.disabled=!a.overridespeeds;T.addEventListener("change",function(){chrome.storage.local.set({speedvariation:parseFloat(this.value)})});
x.checked=a.controlspeed;x.addEventListener("click",function(){V.disabled=!this.checked;chrome.storage.local.set({controlspeed:this.checked})});V.checked=a.controlspeedmousebutton;V.disabled=!a.controlspeed;V.addEventListener("click",g);h.checked=a.defaultvolume;h.addEventListener("click",function(){U.disabled=!this.checked;chrome.storage.local.set({defaultvolume:this.checked})});U.value=a.volume;U.disabled=!a.defaultvolume;U.addEventListener("input",function(){a.volume=Number(this.value);Fa.textContent=
a.volume;chrome.storage.local.set({volume:a.volume})});Fa.textContent=a.volume;t.value=a.volumemultiplier;t.addEventListener("change",function(){chrome.storage.local.set({volumemultiplier:Number(this.value)})});N.checked=a.controlvolume;N.addEventListener("click",function(){W.disabled=!this.checked;X.disabled=!this.checked;chrome.storage.local.set({controlvolume:this.checked})});W.checked=a.controlvolumemousebutton;W.disabled=!a.controlvolume;W.addEventListener("click",g);X.value=a.volumevariation;
X.disabled=!a.controlvolume;X.addEventListener("change",function(){chrome.storage.local.set({volumevariation:Number(this.value)})});t.value=a.volumemultiplier;t.addEventListener("change",function(){chrome.storage.local.set({volumemultiplier:Number(this.value)})});Ga.checked=a.miniplayer;Ga.addEventListener("click",function(){Y.disabled=!this.checked;Z.disabled=!this.checked;chrome.storage.local.set({miniplayer:this.checked})});Y.value=a.miniplayersize;Y.disabled=!a.miniplayer;Y.addEventListener("change",
g);Z.value=a.miniplayerposition;Z.disabled=!a.miniplayer;Z.addEventListener("change",g);d=b.querySelector("#blockautoplay");var aa=b.querySelector("#pauseforegroundtab"),ba=b.querySelector("#ignoreplaylists"),ca=b.querySelector("#stopvideos");d.checked=a.blockautoplay;d.addEventListener("click",function(){aa.disabled=!this.checked;ba.disabled=!this.checked;ca.disabled=!this.checked;chrome.storage.local.set({blockautoplay:this.checked})});aa.checked=a.pauseforegroundtab;aa.disabled=!a.blockautoplay;
aa.addEventListener("click",g);ba.checked=a.ignoreplaylists;ba.disabled=!a.blockautoplay;ba.addEventListener("click",g);ca.checked=a.stopvideos;ca.disabled=!a.blockautoplay;ca.addEventListener("click",g);d=b.querySelector("#pausevideos");var da=b.querySelector("#ignorepopupplayer");d.checked=a.pausevideos;d.addEventListener("click",function(){da.disabled=!this.checked;chrome.storage.local.set({pausevideos:this.checked})});da.checked=a.ignorepopupplayer;da.disabled=!a.pausevideos;da.addEventListener("click",
g);d=b.querySelector("#disableautoplay");var Ha=b.querySelector(".autoplay-toggle-button");d.checked=a.disableautoplay;Ha.setAttribute("aria-checked",!a.disableautoplay);d.addEventListener("click",function(){Ha.setAttribute("aria-checked",!this.checked);chrome.storage.local.set({disableautoplay:this.checked})});var sa=b.querySelector("#selectquality"),y=b.querySelector("#selectqualityfullscreenon"),O=b.querySelector("#selectqualityfullscreenoff"),ea=["#qualityvideos","#qualityplaylists","#qualityembeds"],
fa=["#qualityvideosfullscreen","#qualityplaylistsfullscreen","#qualityembedsfullscreen"];sa.checked=a.selectquality;sa.addEventListener("click",function(){ea.forEach(c=>{b.querySelector(c).disabled=!sa.checked});y.disabled=!this.checked;this.checked?(ea.forEach(c=>{b.querySelector(c).disabled=!1}),y.disabled=!1,y.checked&&(fa.forEach(c=>{b.querySelector(c).disabled=!1}),O.disabled=!1)):(ea.forEach(c=>{b.querySelector(c).disabled=!0}),y.disabled=!0,fa.forEach(c=>{b.querySelector(c).disabled=!0}),O.disabled=
!0);chrome.storage.local.set({selectquality:this.checked})});ea.forEach(c=>{c=b.querySelector(c);c.value=a[c.id];c.disabled=!a.selectquality;c.addEventListener("change",g)});y.checked=a.selectqualityfullscreenon;y.addEventListener("click",function(){fa.forEach(c=>{b.querySelector(c).disabled=!y.checked});O.disabled=!this.checked;chrome.storage.local.set({selectqualityfullscreenon:this.checked})});fa.forEach(c=>{c=b.querySelector(c);c.value=a[c.id];c.disabled=!a.selectqualityfullscreenon;c.addEventListener("change",
g)});O.checked=a.selectqualityfullscreenoff;O.addEventListener("click",g);d=b.querySelector("#popuplayersize");d.value=a.popuplayersize;d.addEventListener("change",g);var ta=b.querySelector("#darktheme"),z=b.querySelectorAll('input[name="theme"]'),D=b.querySelector("#themevariant"),E=b.querySelector("#vendorthemevariant");h=b.querySelector("#customtheme");var ha=b.querySelector("#customcss");t=b.querySelector("#customcss-btn");var ia=b.querySelector("#customcss-checkmark");d=z.length-1;ta.checked=
a.darktheme;for(ta.addEventListener("click",function(){z.forEach(c=>{c.disabled=!ta.checked});this.checked?(D.disabled="enhanced-dark"===b.querySelector('input[name="theme"]:checked').value?!1:!0,E.disabled="youtube-deep-dark"===b.querySelector('input[name="theme"]:checked').value?!1:!0,Q()):(D.disabled=!0,E.disabled=!0,n.forEach(c=>{c.disabled=!0}),R.disabled=!0);chrome.storage.local.set({darktheme:this.checked})});0<=d;d--)z[d].value===a.theme&&(z[d].checked=!0),z[d].disabled=!a.darktheme,z[d].addEventListener("click",
g),z[d].addEventListener("click",function(){D.disabled="enhanced-dark"===this.value?!1:!0;E.disabled="youtube-deep-dark"===this.value?!1:!0;Q()});D.value=a.themevariant;D.disabled=a.darktheme?"enhanced-dark"===a.theme?!1:!0:!0;D.addEventListener("change",g);E.value=a.vendorthemevariant;E.disabled=a.darktheme?"youtube-deep-dark"===a.theme?!1:!0:!0;E.addEventListener("change",g);x=a.customcolors;for(d=n.length-1;0<=d;d--)n[d].disabled=!a.darktheme,n[d].value=x[n[d].name],n[d].addEventListener("change",
ya);R.disabled=!a.darktheme;R.addEventListener("click",()=>{var c=F.customcolors;n.forEach(f=>{f.value=c[f.name]});ya()});Q();h.checked=a.customtheme;h.addEventListener("click",function(){chrome.storage.local.set({customtheme:this.checked})});ha.disabled=!a.customtheme;ha.value=a.customcss;ha.addEventListener("focus",()=>{ia.classList.remove("show")});t.disabled=!a.customtheme;t.addEventListener("click",()=>{ia.classList.add("show");chrome.storage.local.set({customcss:ha.value})});ia.addEventListener("animationend",
c=>{"checkmark-scale"===c.animationName&&setTimeout(()=>{ia.classList.remove("show")},1200)});var ua=b.querySelector("#customscript");d=b.querySelector("#customscript-btn");var ja=b.querySelector("#customscript-checkmark");ua.value=a.customscript;ua.addEventListener("focus",()=>{ja.classList.remove("show")});d.addEventListener("click",()=>{ja.classList.add("show");chrome.storage.local.set({customscript:ua.value})});ja.addEventListener("animationend",c=>{"checkmark-scale"===c.animationName&&setTimeout(()=>
{ja.classList.remove("show")},1200)});e=a.griditemsperrow;d=b.querySelector("#videos-per-row");var ka=b.querySelector("#videos-per-row-count");h=b.querySelector("#channel-videos-per-row");var la=b.querySelector("#channel-videos-per-row-count");t=b.querySelector("#shorts-per-row");var ma=b.querySelector("#shorts-per-row-count");x=b.querySelector("#channel-shorts-per-row");var na=b.querySelector("#channel-shorts-per-row-count");N=b.querySelector("#posts-per-row");var oa=b.querySelector("#posts-per-row-count");
d.checked=e.videos.apply;d.addEventListener("click",function(){e.videos.apply=this.checked;ka.disabled=!this.checked;q()});ka.value=e.videos.count;ka.disabled=!e.videos.apply;ka.addEventListener("change",function(){e.videos.count=parseFloat(this.value);q()});h.checked=e.channel.videos.apply;h.addEventListener("click",function(){e.channel.videos.apply=this.checked;la.disabled=!this.checked;q()});la.value=e.channel.videos.count;la.disabled=!e.channel.videos.apply;la.addEventListener("change",function(){e.channel.videos.count=
parseFloat(this.value);q()});t.checked=e.shorts.apply;t.addEventListener("click",function(){e.shorts.apply=this.checked;ma.disabled=!this.checked;q()});ma.value=e.shorts.count;ma.disabled=!e.shorts.apply;ma.addEventListener("change",function(){e.shorts.count=parseFloat(this.value);q()});x.checked=e.channel.shorts.apply;x.addEventListener("click",function(){e.channel.shorts.apply=this.checked;na.disabled=!this.checked;q()});na.value=e.channel.shorts.count;na.disabled=!e.channel.shorts.apply;na.addEventListener("change",
function(){e.channel.shorts.count=parseFloat(this.value);q()});N.checked=e.posts.apply;N.addEventListener("click",function(){e.posts.apply=this.checked;oa.disabled=!this.checked;q()});oa.value=e.posts.count;oa.disabled=!e.posts.apply;oa.addEventListener("change",function(){e.posts.count=parseFloat(this.value);q()});d=b.querySelector("#export-modal-btn");h=b.querySelector("#import-modal-btn");var m=b.querySelector("#backup-modal"),Ia=m.querySelector(".close-modal"),Ja=m.querySelector("#export-modal-content"),
Ka=m.querySelector("#export-textarea"),La=m.querySelector("#import-modal-content"),va=m.querySelector("#import-error"),pa=m.querySelector("#import-textarea"),wa=m.querySelector("#import-btn"),xa=m.querySelector("#copy-to-clipboard-btn"),P=m.querySelector("#copy-to-clipboard-checkmark");d.addEventListener("click",()=>{Ja.classList.remove("hidden");xa.classList.remove("hidden");P.classList.remove("hidden");qa(m);chrome.storage.local.get(null,c=>{var f={};f.version=chrome.runtime.getManifest().version;
f.settings={};Object.keys(F).forEach(k=>{f.settings[k]=void 0===c[k]?F[k]:c[k]});Ka.value=JSON.stringify(f,null,2)})});h.addEventListener("click",()=>{La.classList.remove("hidden");wa.classList.remove("hidden");qa(m)});Ia.addEventListener("click",()=>{Aa(m);setTimeout(()=>{Ja.classList.add("hidden");La.classList.add("hidden");va.classList.add("hidden");wa.classList.add("hidden");xa.classList.add("hidden");P.classList.add("hidden");pa.value=""},600)});xa.addEventListener("click",async()=>{await navigator.clipboard.writeText(Ka.value);
P.classList.add("show")});P.addEventListener("animationend",c=>{"checkmark-scale"===c.animationName&&setTimeout(()=>{P.classList.remove("show")},1200)});wa.addEventListener("click",async()=>{var c=pa.value.trim();if(""!==c){try{c=JSON.parse(c)}catch(k){va.classList.remove("hidden");pa.value=k;return}if("object"===typeof c.settings&&c.version&&(/^3\.\d+\.\d+/.test(c.version)||/^2\.0\.1(0[2-9]|[1-2][0-9])/.test(c.version))){Array.isArray(c.settings.controls)&&(c.settings.controls=c.settings.controls.filter(A=>
"whitelist"!==A&&"not-interested"!==A));c.settings.backgroundcolor&&(c.settings.backdropcolor=c.settings.backgroundcolor,delete c.settings.backgroundcolor);c.settings.backgroundopacity&&(c.settings.backdropopacity=c.settings.backgroundopacity,delete c.settings.backgroundopacity);c.settings.customcssrules&&(c.settings.customcss=c.settings.customcssrules,delete c.settings.customcssrules);c.settings.miniplayersize&&(c.settings.miniplayersize=c.settings.miniplayersize.replace("_",""));c.settings.miniplayerposition&&
(c.settings.miniplayerposition=c.settings.miniplayerposition.replace("_",""));"default-light"===c.settings.theme&&(c.settings.theme="default-dark");let k;if(null==(k=c.settings.themevariant)?0:k.includes("youtube-deep-dark"))c.settings.vendorthemevariant=c.settings.themevariant.replace("-youtube-light",""),delete c.settings.themevariant;var f={};Object.keys(c.settings).forEach(A=>{typeof F[A]===typeof c.settings[A]&&(f[A]=c.settings[A])});await chrome.storage.local.clear();chrome.storage.local.set(f,
()=>{w.scrollTo(0,0);b.location.reload()})}else va.classList.remove("hidden"),!c.version||/^3\.\d+\.\d+/.test(c.version)&&/^2\.0\.1(0[2-9]|[1-2][0-9])/.test(c.version)||(pa.value="Outdated backup...")}});b.addEventListener("keydown",c=>{"Escape"===c.key&&("block"===m.style.display?Ia.click():"block"===C.style.display&&Ca.click())})});window.addEventListener("resize",Ba);Ba();b.addEventListener("transitionend",a=>{a=a.target;a===u?(a=u.getBoundingClientRect(),0>=a.left?u.style.setProperty("left","calc("+
a.width/2+"px + .5rem)"):a.right>b.documentElement.clientWidth&&u.style.setProperty("left","calc("+(b.documentElement.clientWidth-a.width/2)+"px - .5rem)")):"FIELDSET"===a.nodeName&&a.classList.remove("highlighted")})})(document,config);